support http/2 response trailers
mitmproxy/mitmproxy pull request #4489
Opened 2021-03-10 02:05 UTC by sanlengjingvv

#### Description

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

2021-03-10 17:35 UTC, mhils requested changes
Hi @sanlengjingvv, thanks for the PR! I'm sorry that your previous HTTP/2 implementation got taken out when we switched to the new proxy core. I appreciate the effort here, but the implementation you are proposing here has the issue that trailers between concurrent flows may be mixed up. We need to define RequestTrailers/ResponseTrailers in [_events.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/layers/http/_events.py), emit them when receiving trailers, extend [HttpStream](https://github.com/mitmproxy/mitmproxy/blob/a00f247f0edfb303bd54cb1f0b7b4e97c4a56fd0/mitmproxy/proxy/layers/http/__init__.py#L93) to accomodate for that, and then add tests. I do have that on my radar, but it's admittedly not a high priority item at the moment (https://github.com/mitmproxy/mitmproxy/issues/4348). If you would like to give it a stab I'd be more than happy to help and explain things, feel free to ping me on Slack as well!

2021-03-14 13:22 UTC, mhils requested changes
This looks great, thanks for the PR! 🍰 Some comments below. 😃

2021-03-14 13:22 UTC, mhils commented on mitmproxy/proxy/layers/http/_http2.py
> +            pseudo_trailers, trailers = split_pseudo_headers(event.headers)
https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.1:

> Pseudo-header fields MUST NOT appear in trailers. 

So we can skip that here :)

2021-03-15 16:22 UTC, mhils reviewed
Thanks for the quick iteration! I have played around with this a bit further, added some streaming tests and then fixed a few streaming-related bugs. 

The most important change is that I have removed the requesttrailers/responsetrailers hooks. Instead, `request` and `response` now always fire after trailers have been received, but before they are forwarded. Can you test if things work for you as expected?

2021-03-16 06:26 UTC, sanlengjingvv commented
Replaying a request with trailers will get an error
> Unexpected event during replay: <module 'mitmproxy.proxy.events' from '/Users/niconi/mitmproxy/mitmproxy/proxy/events.py'>

2021-03-16 09:22 UTC, mhils commented
Fixed for me locally, does it work for you as well now? 😃

2021-03-16 09:43 UTC, sanlengjingvv commented
> Fixed for me locally, does it work for you as well now? 😃

Yes, it works for me now.

2021-03-16 11:09 UTC, mhils approved these changes

2021-03-16 11:13 UTC, mhils commented
Excellent. Thanks again for the initial PR and getting this going! 😃 🍰

2021-03-16 11:13 UTC, merged