Fix multipart forms losing `boundary` values on edit
mitmproxy/mitmproxy pull request #4625
Opened 2021-06-08 01:53 UTC by roytu

#### Description

This is a fix for issue #4613 .  The problem is that in several places where multipart is used, the code assumes that the header will match `Content-Type: multipart/form-data` *exactly*, whereas the reality often has `Content-Type: multipart/form-data; boundary=---------foo`.

#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

2021-06-08 09:10 UTC, mhils requested changes
Thanks! This looks like a good catch. I've added some comments below. In short, we can take contentviews out of the picture, and then change the multipart setter to actually work. 😃

2021-06-08 09:10 UTC, mhils commented on mitmproxy/contentviews/__init__.py
> +                content_type = http.assemble_content_type(ct[0], ct[1], ct[2])
I believe we never need the content type attributes when selecting a contentview? Unless there's something I am missing, please revert the changes here.

2021-06-08 09:10 UTC, mhils commented on mitmproxy/contentviews/multipart.py
> +        if content_type and content_type.startswith("multipart/form-data"):
see above - this is only used to select the correct view, we don't need to handle the boundary information here.

2021-06-08 09:10 UTC, mhils commented on mitmproxy/http.py
> +            self.headers["content-type"] = "multipart/form-data"
This... looks like it plainly didn't work before? Good catch.

I would suggest we change the logic here to 

1. Check if `self.headers["content_type"].startswith("multipart/form-data")`, and if that's not the case, add a content-type header with a random (?) boundary. The point here is that if someone assigns to `.multipart_form = ` in their addon, the header should be updated accordingly if the request was not multipart before.
2. *After* that, call `self.content = multipart.encode(self.headers, value)` (as we do right now)

2021-06-08 21:34 UTC, roytu commented
Thanks for the comments :)

Added commits to revert the `contentviews` stuff and the fix still seems to work, so I believe you're correct that the content type attributes aren't used there.

Also updated the `set_multipart_form` function to generate a boundary if the header doesn't exist (stole it from https://github.com/urllib3/urllib3/blob/2ef05adfcf001c85f1f95ae3fa078d16190851b0/src/urllib3/filepost.py#L20-L24 and added a few dashes for readability).

2021-06-09 10:19 UTC, mhils approved these changes
This looks fantastic now, thanks for the quick turnaround! 🍰 😃

2021-06-09 10:26 UTC, merged