fix map remote addon not setting `Host` header correctly
mitmproxy/mitmproxy pull request #5908
Opened 2023-02-04 10:56 UTC by sujaldev

#### Description

Fixes #5907

#### Checklist

 - [x] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

2023-02-04 11:06 UTC, sujaldev commented
Seems like I screwed up, trying to fix it :(

2023-02-04 14:21 UTC, mhils requested changes
This requires significantly more thought. We want to update the host header and `.authority` both on updates to `.host` as well as on updates to `.port`. This also requires extensive testing. For example, the current PR will fail for `req.port = 42; req.port = 44`

2023-02-05 11:21 UTC, mhils reviewed
Nice, this looks much better now! 😃

2023-02-05 11:21 UTC, mhils commented on mitmproxy/http.py
> +            # test_http.py::TestRequestCore::test_port sets port = b"foo" as the port
Let's check that `port` is an `int` in `port.setter` and raise a ValueError if that's not the case. We can then adjust the test and skip this check here :)

2023-02-05 13:41 UTC, mhils approved these changes

2023-02-06 16:35 UTC, merged