Multiple flows selection
mitmproxy/mitmproxy pull request #7319
Opened 2024-11-12 19:54 UTC by lups2000

#### Description

In this PR, I'm introducing the ability to select multiple flow rows by pressing `Ctrl` (or `Command` on macOS) and clicking on the flow. The main purpose of this PR is to support the deletion of selected flows.

#### Checklist

 - [ ] I have updated tests where applicable.
 - [ ] I have added an entry to the CHANGELOG.

2025-01-06 08:36 UTC, Prinzhorn requested changes

2025-01-06 08:36 UTC, Prinzhorn commented on web/src/js/components/FlowTable.tsx
> +    selectedFlows: string[];
`selectedFlowIds`?

2025-01-06 08:36 UTC, Prinzhorn commented on web/src/js/ducks/flows.ts
>      selected: string[];
I'm confused why here `selected` has always been a `string[]` but in a different part `select` was `Flow` and now became `selectedFlows` as `string[]`?

2025-01-06 08:36 UTC, Prinzhorn commented on web/src/js/components/MainView.tsx
> +    const isMultipleFlowsSelection = useAppSelector(
I don't quite understand why `isMultipleFlowsSelection` exists? In most parts of the UI you use `selectedFlows.length > 1` but then in this one part you use this flag instead. Either consistently track `isMultipleFlowsSelection` or consistently imply it via `selectedFlows.length > 1`. Or am I misunderstanding what's happening?

2025-01-06 08:36 UTC, Prinzhorn commented on web/src/js/ducks/flows.ts
>                  selected: action.flowIds,
Shouldn't this be `selected: [action.flowIds],`?

2025-01-15 07:22 UTC, lups2000 commented on web/src/js/ducks/flows.ts
>                  selected: action.flowIds,
`action.flowIds` is already an array of strings. Using `[action.flowIds]` would create an array containing an array of strings

2025-01-15 07:47 UTC, lups2000 commented on web/src/js/components/MainView.tsx
> +    const isMultipleFlowsSelection = useAppSelector(
you're right, having both sounds confusing! I've removed `isMultipleFlowsSelection`

2025-02-16 10:19 UTC, mhils reviewed
I think this is super valuable, and it's a good idea to start small here and only support deletions. Left a few comments below, but please also add at least a test to select/deselect a second flow with Ctrl+Click. :)

2025-02-16 10:19 UTC, mhils commented on web/src/js/ducks/flows.ts
> +export function removeMultiple(flowIds: string[]) {
I think the general pattern of adding separate "multi" actions isn't great. Why don't we change the existing `remove` action to always accept a list of flow ids? It's not used in a million places, we can easily adapt existing callsites. :)

2025-02-16 10:19 UTC, mhils commented on web/src/js/ducks/flows.ts
> +export function multiSelect(id: string) {
Same here.

2025-02-16 10:19 UTC, mhils commented on web/src/js/components/MainView.tsx
> +    );
```suggestion
    const hasFlowSelected = useAppSelector(
        (state) => state.flows.selected.length === 1 && !!state.flows.byId[state.flows.selected[0]],
    );
```

The primary benefit of this change is that you will need to address the other usage of `hasSelection` and fix it in the process. No need for a splitter if there's no flow view 😉

2025-02-16 10:19 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +    const selectedFlows = useAppSelector((state) => state.flows.selected);
Add a TODO comment here for multi-selection to indicate intent (it can/should be done, it just hasn't been done yet).

2025-02-16 10:19 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +    const selectedFlows = useAppSelector((state) => state.flows.selected);
`useAppSelector` is instrumental for caching, see https://redux.js.org/tutorials/fundamentals/part-5-ui-react#reading-state-from-the-store-with-useselector. If we only use `selectedFlows` for `selectedFlows.length > 1` checks, we should only return the boolean from the selector.

Considering this is used repeatedly, I wouldn't mind a `selectHasSingleFlowSelected` helper, but both with and without helper is fine. :)

2025-03-01 18:21 UTC, mhils reviewed
Nice progress! 🚀

2025-03-01 18:21 UTC, mhils commented on web/src/js/components/FlowTable/FlowRow.tsx
> +    const selectedFlowsIds = useAppSelector((state) => state.flows.selected); // used for multiple flows selection
Nit:
```suggestion
    const selectedFlowIds = useAppSelector((state) => state.flows.selected); // used for multiple flows selection
```

2025-03-01 18:21 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +    );
I don't think memoization here is helping. We already get the forced rerender from `const selectedFlows = useAppSelector((state) => state.flows.selected);`. Memoizing here isn't going to change this. Two possible ways forward:

1. We decide that performance is good enough here. Then we can just remove the useMemo call and be done with it.
2. We decide that performance is important here. Then we need to get rid of the `useAppSelector((state) => state.flows.selected)` call. In this case we cannot call `removeFlow(selectedFlows)`. Alternatively, we could introduce an `removeSelectedFlows()` action. In this action we would then access the state to get the selected flows and work with that.

Both is fine with me, up to you what makes most sense. :)

2025-03-01 18:21 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +    if (!hasSingleFlowSelected) return null;
Is there a reason why this button is treated differently (removed and not disabled)?

2025-03-01 19:16 UTC, lups2000 commented on web/src/js/components/Header/FlowMenu.tsx
> +    if (!hasSingleFlowSelected) return null;
no my bad, thanks for spotting this :)

2025-03-01 19:42 UTC, lups2000 commented on web/src/js/components/Header/FlowMenu.tsx
> +    );
I would keep it simple and remove the **useMemo**. I don't think we will encounter any significant performance issues here. In most cases, users will select a relatively limited number of flows since they have to do it manually. I tested it with ~50 flows, and it runs smoothly. Does that make sense to you?

2025-03-01 21:24 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +    );
SGTM

2025-03-02 06:47 UTC, lups2000 commented on web/src/js/components/Header/FlowMenu.tsx
> +    );
perfect :)

2025-03-17 17:25 UTC, mhils approved these changes
This looks fantastic now, thanks! One small perf optimization, feel free to merge yourself after. 😃

2025-03-17 17:25 UTC, mhils commented on web/src/js/components/FlowTable.tsx
> +            );
Perf: The store maintains a flowId -> index mapping:
https://github.com/mitmproxy/mitmproxy/blob/6269898b434e1040c4ea46a425526c5d266c554b/web/src/js/ducks/utils/store.ts#L25

2025-03-18 20:36 UTC, lups2000 commented on web/src/js/components/Header/FlowMenu.tsx
> +                                dispatch(selectFlow([])); // clear flow selection
I noticed a small bug: previously, when a user removed a flow, the next flow was automatically selected. Now, this no longer happens. It would be nice to keep that behaviour, what do you think?
This line seems to be the issue. I remember adding it because, without it, multiple deletions caused this API call:

`http://127.0.0.1:8081/flows/e394b6f1-7425-40ec-9387-c72d949feee6/request/content/Auto.json?lines=513
`

to fail with a **404 Not Found**. This happens because the flow ID is selected as the next flow even though it has already been deleted. After this failed call, we correctly call the endpoint again with the actual next flow, and everything works fine.
Now, I need to figure out how to solve that 😄

2025-03-19 08:22 UTC, mhils commented on web/src/js/components/Header/FlowMenu.tsx
> +                                dispatch(selectFlow([])); // clear flow selection
Great catch! This one is important. Folks coming from the TUI will repeatedly press `d` to get rid of flows. 😄

2025-03-22 07:34 UTC, lups2000 commented on web/src/js/components/Header/FlowMenu.tsx
> +                                dispatch(selectFlow([])); // clear flow selection
okay this is solved now

2025-03-22 07:39 UTC, lups2000 commented on web/src/js/components/FlowTable.tsx
> +            );
Regarding this, I replaced that line with **listIndex**, and it worked fine. However, during testing, I encountered the following error:

"_Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops_"

I had to add this statement 
```
if (!shallowEqual(this.props.flowIndexes, prevProps.flowIndexes)) {
      this.onViewportUpdate();
}
```
which solved the issue but it introduces some inefficiency again. Do you have any idea?

2025-04-23 19:34 UTC, lups2000 commented
Looks good to me @mhils . Maybe we can update the changelog entry to be more accurate.

2025-04-25 07:07 UTC, lups2000 commented
<img width="1512" alt="Screenshot 2025-04-25 at 09 06 46" src="https://github.com/user-attachments/assets/bfc82bef-9249-447e-b325-9a52af25331e" />

when selecting a flow

2025-04-25 08:23 UTC, lups2000 commented
@mhils I have fixed a couple of issues:
1. A crash that occurred when selecting a flow (see image above).
2. An error when removing multiple flows; same issue as described here: https://github.com/mitmproxy/mitmproxy/pull/7319#discussion_r2001960571
3. Previously, it was sometimes impossible to clear all flows, because removing the last one would throw: `Cannot read property 'id' of undefined`

 would you mind taking a final look ? thank you 😄

2025-04-25 10:16 UTC, lups2000 commented on web/src/js/ducks/flows.ts
> +                selected = [];
If we enter this branch, it means we want to remove more than one element, and after removing the flows, the selection is cleared. How is it possible that only one of the selected flows gets removed and not everything?
Without this change, if you try to remove multiple flows we get a 404 Not found exception.

2025-04-25 11:33 UTC, mhils commented on web/src/js/ducks/flows.ts
> +                selected = [];
> If we enter this branch, it means we want to remove more than one element

This is not true AFAIK. `REMOVE` is triggered individually for every flow in the backend.

> Without this change, if you try to remove multiple flows we get a 404 Not found exception.

Only in the devtools, not user visible, correct?

This is a race: If we have two selected flows (A and B) and click remove, that's currently two requests. Both will reach the backend at about the same time, then for both we get a REMOVE event. After the first REMOVE (of A) the selection switches to B only. The frontend then tries to get the view for B, but B has already been removed in the backend (the frontend hasn't learned about this yet).

One way to fix this race is to batch the `POST /remove` requests and also the resulting event. But honestly I'm fine with how things are at the moment. Fundamentally, user A can always select flow X which has just been deleted in the backend (which will trigger a 404). Those are harmless IMO. :)

2025-04-25 13:34 UTC, lups2000 commented
I've implemented marking for multiple flows as well. The only thing missing now is replay, but we can leave that for another PR; this one’s already big enough 😅. All good?

2025-04-25 15:09 UTC, mhils commented on web/src/js/ducks/flows.ts
> +): Pick<FlowsState, "selected" | "selectedIndex"> {
We need to fix the lack of test coverage here, otherwise this PR is good to go. 👍

2025-04-25 19:55 UTC, lups2000 commented on web/src/js/ducks/flows.ts
> +): Pick<FlowsState, "selected" | "selectedIndex"> {
I added some tests to cover those lines. Let me know :)

2025-04-27 10:21 UTC, mhils approved these changes
🚀🚀🚀

2025-04-27 10:21 UTC, merged

2025-05-07 16:05 UTC, jeromesegura commented
> I've implemented marking for multiple flows as well. The only thing missing now is replay, but we can leave that for another PR; this one’s already big enough 😅. All good?

Love the new feature! mitmweb has a lot of potential as a full client for those that prefer this kind of user experience. Right click support on individual flows would be amazing ;-)

2025-05-07 16:40 UTC, mhils commented
What would you like to see in a right-click menu? 

FWIW, one of the next things on the mitmweb front I would like to tackle is https://github.com/mitmproxy/mitmproxy/issues/7694.

(Needless to say: contributions are welcome! ;-))

2025-05-07 18:02 UTC, jeromesegura commented
> What would you like to see in a right-click menu?
> 
> FWIW, one of the next things on the mitmweb front I would like to tackle is #7694.
> 
> (Needless to say: contributions are welcome! ;-))

I will reply in that thread with more details, thanks!